### PR TITLE
[MNG-7661] Replace deprecated 'verifier.executeGoal()'

### PR DESCRIPTION
**Pull request by psiroky**
Another PR in the series, replacing the deprecated method `executeGoal(<goal>)` with `addCliArgumenet(<goal) + execute()` as per the suggestion in the verifier Javadoc.

### CODE REVIEW

**Comment by hboutemy** [comment]
@slawekjaranowski @psiroky it seems the recent changes broke one IT:
```
Error:    MavenITmng7112ProjectsWithNonRecursiveTest.testAggregatesCanBeDeselectedNonRecursively:71 » Verification Exit code was non-zero: 1; command line and log = 
/home/runner/work/maven/maven/maven-integration-testing/core-it-suite/target/apache-maven/bin/mvn -e --batch-mode -Dmaven.repo.local=/home/runner/.m2/repository --global-settings /home/runner/work/maven/maven/maven-integration-testing/core-it-suite/target/test-classes/settings.xml
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Maven Integration Test :: MNG-7112                                 [pom]
[INFO] aggregator-a                                                       [pom]
[INFO] module-a                                                           [jar]
[INFO] aggregator-b                                                       [pom]
[INFO] module-b                                                           [jar]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Maven Integration Test :: MNG-7112 1.0:
[INFO] 
[INFO] Maven Integration Test :: MNG-7112 ................. SKIPPED
[INFO] aggregator-a ....................................... SKIPPED
[INFO] module-a ........................................... SKIPPED
[INFO] aggregator-b ....................................... SKIPPED
[INFO] module-b ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.013 s
[INFO] Finished at: 2023-01-11T00:12:36Z
[INFO] ------------------------------------------------------------------------
Error:  No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: pre-clean, clean, post-clean, validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site, site-deploy, wrapper. -> [Help 1]
```

visible at #949 PR build on GH CI, but surprisingly not on Jenkins https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven/view/change-requests/job/PR-949/

**Comment by psiroky** [comment]
Sorry about that. I will take a look asap.

**Comment by psiroky** [comment]
Here is a proposed fix https://github.com/apache/maven-integration-testing/pull/227.

It seems like the test also failed in the linked Jenkins build. Looking into the [job output](https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven/view/change-requests/job/PR-949/3/execution/node/123/log/?consoleFull):
```
...
[ERROR] Tests run: 886, Failures: 0, Errors: 2, Skipped: 35
...
```
It seems to me the job is misconfigured since it is still "green" even if some of the tests fail.

**Comment by hboutemy** [comment]
> It seems to me the job is misconfigured since it is still "green" even if some of the tests fail.
uhhhh...

thanks for your hard work

**Comment by hboutemy** [comment]
@olamy any idea on the Jenkins job for Core ITs not picking ITs failures?

**Comment by psiroky** [comment]
I think I found the cause - see my comment https://github.com/apache/maven/commit/3f336e4f6d63e958bdd96d5e90910a4cbd9ad1db#r95760514. Let me try to create a PR with a fix.

**Pull request merged**
