### PR TITLE
[MNG-7338] Disable CI mode for certain tests which verify on log statements.

### PR DESCRIPTION
**Pull request by MartinKanters**
Relevant [Maven PR](https://github.com/apache/maven/pull/869)

### CODE REVIEW

**Comment by michael-o** [comment]
I don't really think it is not in the spirit of this var. As far as I understand it is either `CI=true` or not present at all.

**Comment by MartinKanters** [comment]
> I don't really think it is not in the spirit of this var. As far as I understand it is either `CI=true` or not present at all.

I agree. I tried to remove it using `verifier.getEnvironmentVariables().remove( "CI" );`, but that doesn't work unfortunately. 
I would not like to change the actual environment variables on the machine if possible, so I thought this was the best way forward.

**Comment by rmannibucau** [comment]
@michael-o it is the defined semantic now but was not originally and it was soletimes used to switch between vendors. That said can not be critical due to the impact.

**Comment by slawekjaranowski** [comment]
> I agree. I tried to remove it using `verifier.getEnvironmentVariables().remove( "CI" );`, but that doesn't work unfortunately.

Should work with:

```
verifier.addEnvironemnt( "CI", null );
```

but needs a maven-sahred-utils 3.3.4 ... as I see 0.9 is used in tests 😄

**Comment by MartinKanters** [comment]
> > I agree. I tried to remove it using `verifier.getEnvironmentVariables().remove( "CI" );`, but that doesn't work unfortunately.
> 
> Should work with:
> 
> ```
> verifier.addEnvironemnt( "CI", null );
> ```
> 
> but needs a maven-sahred-utils 3.3.4 ... as I see 0.9 is used in tests 😄

Right.. not sure if that's worth the effort for this change haha. I tried it quickly but didn't see an addEnvironment variable method. I did see that invoking setEnvironment with a `null` value should remove it from the environment variables. But that didn't work before. I think that's because those environment vars are probably merged later with the actual environment variables (which would add CI=true again)

**Pull request merged**
