### PR TITLE
[MNG-7020] Remove Maven 2 WagonExcluder backward compat code

### PR DESCRIPTION
**Pull request by michael-o**
* Disable unused tests
* Update Maven 2 plugins to Maven 3 to avoid conflicts with old Maven
  and Wagon 1

### CODE REVIEW

**Comment by mthmulders** [comment]
I'm afraid the rebase missed cb3d4a9...

**Comment by michael-o** [comment]
> I'm afraid the rebase missed [cb3d4a9](https://github.com/apache/maven-integration-testing/commit/cb3d4a96c8005528b91cc3439e1fc83f3814469a)...

Seems o,

**Comment by michael-o** [comment]
Pushed rebased tree.

**Comment by michael-o** [comment]
@mthmulders Ran ITs locally, all pass. The GH Actions aren't up to date and I don't know why.

**Comment by mthmulders** [comment]
Double checked, the `-fos`-related fix is in this branch, too. Double-checking [the GH Action run](https://github.com/apache/maven/runs/4753755945?check_suite_focus=true) it seems it's mixing old and new results - in the last attempts, everything is green as grass.

**Pull request merged**
