### PR TITLE
Use Maven 3.9.4 on GitHub

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by michael-o — CHANGES_REQUESTED** [review]
I wouldn't do this before at least 3.9.1, .0 contains too many open issues for now.

**Comment by slawekjaranowski** [comment]
I would like to go a step forward and also add 4.x 
After review of #238 I found issue with 4.x
Simply we should have a possibility to detect an issue early

What do you think?

**Review by slachiewicz — APPROVED** [review]

**Comment by mthmulders** [comment]
How about a matrix, with Maven 3.9.x and 4.0.0-alpha-x (where `x` is latest for both)?

**Comment by slawekjaranowski** [comment]
> How about a matrix, with Maven 3.9.x and 4.0.0-alpha-x (where `x` is latest for both)?

I'm not sure about matrix build here - it should be a simple test for changing in repo.
We execute ITs when Maven build itself for specific change.

**Comment by slawekjaranowski** [comment]
> I wouldn't do this before at least 3.9.1, .0 contains too many open issues for now.

I hope that 3.9.4 is better than 3.9.1 😄

**Review by michael-o — APPROVED** [review]

**Review by cstamas — APPROVED** [review]

**Pull request merged**
