### PR TITLE
[MNG-7464] Warn about using read-only parameters for Mojo in configuration

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by michael-o** [comment]
Question: So settings these is a no-op, true?
I wonder whether we'd like to have this warning in 3.9.0 as well.

**Comment by pzygielo** [comment]
> Question: So settings these is a no-op, true?

How I checked it:
Set compiler's [`outputDirectory`](https://github.com/apache/maven-compiler-plugin/blob/1d912302d1f4a315b1db18fcc3197cae7796cc4f/src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java#L74). It is respected (at least in maven 3.8.5) and value from pom is used.

I'm 100% sure that _readonlines_ of parameter probably results in not having it in mojo docs only.

**Comment by pzygielo** [comment]
MNG-5001

**Comment by slawekjaranowski** [comment]
> I wonder whether we'd like to have this warning in 3.9.0 as well.

will be in next PR

**Comment by slawekjaranowski** [comment]
is is first step for MAN-5001 ... as we see many plugins should be changed like m-compiler with `outputDirectory` 
if user need override some of parameters those should be not read-only, or plugins should provide another way ...
So only warring

**Comment by pzygielo** [comment]
> is first step for MAN-5001

Indeed - and it's even linked to it. I was blind, but now I see.

**Review by michael-o — APPROVED** [review]

**Pull request merged**
