### PR TITLE
Run MNG-7160 test also for Maven 3.8.8+

### PR DESCRIPTION
**Pull request by famod**
For https://github.com/apache/maven/pull/999

### CODE REVIEW

**Review by michael-o — CHANGES_REQUESTED** [review]
The entire test needs to be back ported to the `maven-3.8.x` branch. Master is for 4 and 3.9.x only.

**Comment by famod** [comment]
Ah, my bad - I missed that somehow. I ran it locally like that and it passed.

Anyway, I'll create another PR then.

**Comment by michael-o** [comment]
> Ah, my bad - I missed that somehow. I ran it locally like that and it passed.
> 
> Anyway, I'll create another PR then.

Not necessary, you can rebase, force push and change the merge base here.

**Comment by famod** [comment]
Turns out the test is already there in the 3.8.x branch.

**Comment by michael-o** [comment]
Change applied.

**Pull request closed without merging**
