### PR TITLE
[MNG-7737] IT for profiles

### PR DESCRIPTION
**Pull request by cstamas**
Just a simple IT that would catch issues like Maven 3.9.0 went out with, where files were wrongly interpolated: MNG-7726

---

https://issues.apache.org/jira/browse/MNG-7737

### CODE REVIEW

**Comment by cstamas** [comment]
Q: shouldn't the POM "pom-active-default" become active as well?

**Comment by slawekjaranowski** [comment]
> Q: shouldn't the POM "pom-active-default" become active as well?

As I know - no, activeByDefault - is only activated when no other profiles are active

From docs:

> This profile will automatically be active for all builds unless another profile in the same POM is activated using one of the previously described methods. All profiles that are active by default are automatically deactivated when a profile in the POM is activated on the command line or through its activation config.

**Comment by cstamas** [comment]
Oh, but then why is "settings-active-default" active?

**Comment by cstamas** [comment]
Seems this is true for POM profiles only: "pom-active-default" gets enabled ONLY when I comment out any other profile in POM. The presence of ANY settings (default or other way activated profile) does not matter.

**Comment by cstamas** [comment]
Verified locally that IT fails w/ 3.9.0 and passes with 3.9.1 (for this the IT range needs change)

**Pull request merged**
