### PR TITLE
Fix version requirement to 4.0.0-alpha-1

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by rfscholte** [comment]
If 4.0.0 is used, are the test skipped? I updated the version in Maven to ensure alpha releases, but it that implies that we get ugly versions here, then I don't mind changing it to 4.0.0

**Comment by michael-o** [comment]
This isn't a problem, when you grep through the code you will find stuff like 3.1.0-alpha-1. Since alpha comes before a GA version, e.g., 4.0.0 this has to work. I will test anyway and let you know. Our version resolution handles this.

**Comment by rfscholte** [comment]
Since @mthmulders offers a brew installation of Mavens master branch, it would be nice to keep the alpha-1 in the version.

**Comment by mthmulders** [comment]
> Since @mthmulders offers a brew installation of Mavens master branch, it would be nice to keep the alpha-1 in the version.

I assume you mean "so that it is very, very clear that these are unstable releases", right?

**Comment by michael-o** [comment]
I do not intend to exchange 3.7.0 for 4.0.0, but for the first alpha as we have done with other tests. ITs are running locally and look good. All previous with 3.7.0 created ITs flawlessly pass with 4.0.0-SNAPSHOT with the 4.0.0-alpha-1 version.

**Comment by michael-o** [comment]
Tests pass, none of the new tests are skips. From my POV this is good to merge.

**Comment by rfscholte** [comment]
@mthmulders exactly. Not sure if 'unstable' is the right word. It should make clear there might be edge cases that we haven't thought of yet and that we expect feedback.

**Comment by mthmulders** [comment]
> @mthmulders exactly. Not sure if 'unstable' is the right word. It should make clear there might be edge cases that we haven't thought of yet and that we expect feedback.

Perfect. Just wanted make sure that those builds should not pose technical limitations on what we think is the best solution to any given problem. They're my personal pet project, not an official community offering, as far as I'm concerned.

**Pull request closed without merging**
