### PR TITLE
[MNG-6939] ITs fail when MAVENCODEBASE is relative

### PR DESCRIPTION
**Pull request by michael-o**
Don't know how to solve it for `cmd`. I am happy with Bourne shell for now.

### CODE REVIEW

**Comment by michael-o** [comment]
@olamy Merci, Robert will add a fix for `cmd` onto this branch.

**Comment by michael-o** [comment]
Will try this on Windows...

**Comment by rfscholte** [comment]
Confirmed, I was already quite happy I managed to fix it for `cmd`. Will have another look at it.

**Comment by michael-o** [comment]
> 
> 
> Confirmed, I was already quite happy I managed to fix it for `cmd`. Will have another look at it.

It works for me when I remove `setlocal`, but don't know the implications.

**Comment by rfscholte** [comment]
removing setlocal meant you couldn't run it for a second time. Hence I introduced a new internal variable.

**Comment by michael-o** [comment]
Going through...

**Comment by michael-o** [comment]
Looks good, will add exit code check for the shell script too

**Comment by michael-o** [comment]
Merged.

**Pull request closed without merging**
