### PR TITLE
Remove pre 3.9.x tests

### PR DESCRIPTION
**Pull request by gnodet**
Extracted from #184 as a separate PR.

### CODE REVIEW

**Review by slawekjaranowski — APPROVED** [review]
Great - I've always thought about it

**Review by michael-o — CHANGES_REQUESTED** [review]
I believe this is incomplete. With a litlte grep and cut magic you have removed these:
```
0036
0039
0145
mng0731
mng1830
mng1908
mng1999
mng2539
mng2562
mng2878
mng2883
mng3057
mng3106
mng3221
mng3271
mng3428
mng3530
mng3599
mng3704
mng3743
mng3760
mng3819
mng3885
mng4086
mng4126
mng4148
mng4254
mng4279
mng5805
mng5889
mng6352
```

but with `grep SKIPPED /tmp/3.9.0.log | grep -v 4.0.0-alpha-1` I get these skipped:
```
0036
0039
0145
mng0469
mng0731
mng1830
mng1908
mng1999
mng2539
mng2562
mng2878
mng2883
mng3057
mng3106
mng3221
mng3271
mng3428
mng3530
mng3599
mng3704
mng3743
mng3760
mng3819
mng3885
mng3933
mng3948
mng3970
mng3983
mng3991
mng4036
mng4086
mng4126
mng4254
mng4279
mng4428
mng5805
mng5889
mng6352
```
so these are missing to be removed:
```
mng0469
mng3933
mng3948
mng3970
mng3983
mng3991
mng4036
mng4428
```
Output:
```
$ grep SKIPPED /tmp/3.9.0.log | grep -f open
mng4428 FollowHttpRedirect.itHttpToHttps()................... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.2.0,2.2.0]
mng4428 FollowHttpRedirect.itHttpsToHttp()................... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.2.0,2.2.0]
mng4036 ParentResolutionFromSettingsRepo.itLegacyLayout().... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-3)
mng3991 ValidDependencyScope.it()............................ SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [4.0,)
mng3983 PluginResolutionFromProfileRepos.itFromProfilesXml(). SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
mng3970 DepResolutionFromProfileRepos.itFromProfilesXml().... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
mng3948 ParentResolutionFromProfileRepos.itFromProfilesXml(). SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
mng3933 ProfilesXmlActivation.itMNG3933().................... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
mng0469 ReportConfig.itReportConfigOverridesBuildDefaults().. SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0.0,3.0-alpha-1)
```

MNG-3991 is bogus, what about the rest?

**Comment by slawekjaranowski** [comment]
Step by step, next can be in next PR 😄

**Comment by michael-o** [comment]
> Step by step, next can be in next PR 😄

Why, I don't understand?

**Comment by slawekjaranowski** [comment]
> > Step by step, next can be in next PR 😄
> 
> Why, I don't understand?

Smaller change are easier for review and probably will be merged faster.
Like in this case we will have better situation.
If we have many comments it take a long time.

**Comment by gnodet** [comment]
> I believe this is incomplete. With a litlte grep and cut magic you have removed these:
> 
> ```
> 0036
> 0039
> 0145
> mng0731
> mng1830
> mng1908
> mng1999
> mng2539
> mng2562
> mng2878
> mng2883
> mng3057
> mng3106
> mng3221
> mng3271
> mng3428
> mng3530
> mng3599
> mng3704
> mng3743
> mng3760
> mng3819
> mng3885
> mng4086
> mng4126
> mng4148
> mng4254
> mng4279
> mng5805
> mng5889
> mng6352
> ```
> 
> but with `grep SKIPPED /tmp/3.9.0.log | grep -v 4.0.0-alpha-1` I get these skipped:
> 
> ```
> 0036
> 0039
> 0145
> mng0469
> mng0731
> mng1830
> mng1908
> mng1999
> mng2539
> mng2562
> mng2878
> mng2883
> mng3057
> mng3106
> mng3221
> mng3271
> mng3428
> mng3530
> mng3599
> mng3704
> mng3743
> mng3760
> mng3819
> mng3885
> mng3933
> mng3948
> mng3970
> mng3983
> mng3991
> mng4036
> mng4086
> mng4126
> mng4254
> mng4279
> mng4428
> mng5805
> mng5889
> mng6352
> ```
> 
> so these are missing to be removed:
> 
> ```
> mng0469
> mng3933
> mng3948
> mng3970
> mng3983
> mng3991
> mng4036
> mng4428
> ```
> 
> Output:
> 
> ```
> $ grep SKIPPED /tmp/3.9.0.log | grep -f open
> mng4428 FollowHttpRedirect.itHttpToHttps()................... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.2.0,2.2.0]
> mng4428 FollowHttpRedirect.itHttpsToHttp()................... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.2.0,2.2.0]
> mng4036 ParentResolutionFromSettingsRepo.itLegacyLayout().... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-3)
> mng3991 ValidDependencyScope.it()............................ SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [4.0,)
> mng3983 PluginResolutionFromProfileRepos.itFromProfilesXml(). SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
> mng3970 DepResolutionFromProfileRepos.itFromProfilesXml().... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
> mng3948 ParentResolutionFromProfileRepos.itFromProfilesXml(). SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
> mng3933 ProfilesXmlActivation.itMNG3933().................... SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0,3.0-alpha-1)
> mng0469 ReportConfig.itReportConfigOverridesBuildDefaults().. SKIPPED - Maven version 3.9.0-SNAPSHOT not in range [2.0.0,3.0-alpha-1)
> ```
> 
> MNG-3991 is bogus, what about the rest?

I worked at the class level, not at method level.  So the 4428 test class is valid for maven 3.9.x, (see https://github.com/apache/maven-integration-testing/blob/ecf4a04cd1c4b7698f28e3332cd24c23116c1467/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4428FollowHttpRedirectTest.java#L57), but a few methods are specific to earlier versions.  I can add a commit or create a new PR for method-level cleanup.

**Review by michael-o — APPROVED** [review]
LGTM. Please squash and merge. I think this is a fundemantal change which should have a JIRA issue.

**Comment by gnodet** [comment]
> LGTM. Please squash and merge. I think this is a fundemantal change which should have a JIRA issue.

Yes, and I think if we should create a branch at that point for pre 3.9 testing and maybe configure the "old" maven  branches to point that branch.

**Comment by michael-o** [comment]
> > LGTM. Please squash and merge. I think this is a fundemantal change which should have a JIRA issue.
> 
> Yes, and I think if we should create a branch at that point for pre 3.9 testing and maybe configure the "old" maven branches to point that branch.

Very good idea!

**Pull request merged**
